### ISSUE TITLE
Possible change to litellm/aisuite

### ISSUE THREAD

**Issue by johacks** [pnmartinez/ai-dashboard-builder#4]
Hi, I saw your project is configured to support many different llm APIs. I've found in the past that [litellm](https://docs.litellm.ai/) makes this a lot easier, as it provides the same API regardless of backend LLM. Would you be interested in a pull request changing the LLM query engine?

Regardless I suggest you check it out because it is an awesome library!

Edit: i've also noticed a [post](https://www.linkedin.com/posts/andrewyng_announcing-new-open-source-python-package-activity-7266851242604134400-Davp?utm_source=share&utm_medium=member_desktop) by andrewNg suggesting aisuite for the same purpose:

**Comment by pnmartinez** [comment]
Hi @johacks ! Thanks for the ideas. They are welcome indeed, I would love frequent contributors.

I'd really appreciate a PR from you. We could then benchmark it and 
- see whether this extra dependencies add overhead (or even the opposite: performance gains)
- how the codebase gets simplified (even reduced).
Then we can make an educated comparison.

Please, go ahead with it and feel free to ping me!
